(define (make-monitored f)
        (define times 0)
        (lambda (x) 
            (cond   ((eq? x 'how-many-calls?) times)
                    ((eq? x 'reset-count) (begin (set! times 0) times))
                    (else (begin (set! times (+ times 1)) (f x))))))

(define s (make-monitored sqrt))
(s 100)
(s 'how-many-calls?)
(s 25)
(s 'how-many-calls?)
(s 'reset-count)
(s 100)
(s 'how-many-calls?)