(define (call-the-cops)
    (display "\nCall the cops"))

(define (make-account balance password)
    (define wrong_pwd_times 0)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin  (set! balance (- balance amount))
                    balance)
            "Insufficient funds"))
    (define (deposit amount)
        (set! balance (+ balance amount))
        balance)
    (define (dispatch pwd m)
        (if (eq? password pwd)
            (begin  (set! wrong_pwd_times 0)
                    (cond   ((eq? m 'withdraw) withdraw)
                            ((eq? m 'deposit) deposit)
                            (else (error "Unknown request: MAKE-ACCOUNT"
                                        m))))
            (begin  (set! wrong_pwd_times (+ wrong_pwd_times 1))
                    (if (> wrong_pwd_times 6)
                        (call-the-cops)
                        (error "Incorrect password")))))
    dispatch)

(define acc (make-account 100 'secret-password))
((acc 'secret-pwd 'withdraw) 40)
((acc 'secret-pwd 'withdraw) 40)
((acc 'secret-pwd 'withdraw) 40)
((acc 'secret-pwd 'withdraw) 40)
((acc 'secret-pwd 'withdraw) 40)
((acc 'secret-pwd 'withdraw) 40)
((acc 'secret-password 'withdraw) 40)
((acc 'secret-pwd 'withdraw) 40)
((acc 'secret-pwd 'withdraw) 40)