(load "3.3.scm")

(define (make-joint acc acc-pwd joint-pwd)
    (define (withdraw amount)
        (if (>= balance amount)
            (begin  (set! balance (- balance amount))
                    balance)
            "Insufficient funds"))
    (define (deposit amount)
        (set! balance (+ balance amount))
        balance)
    (define (dispatch pwd m)
        (if (eq? pwd joint-pwd)
            (acc acc-pwd m)
            (error "Incorrect password")))
    dispatch)

(define peter-acc (make-account 100 'peter-password))
((peter-acc 'peter-password 'withdraw) 10)
(define paul-acc (make-joint peter-acc 'peter-password 'paul-password))
((paul-acc 'paul-password 'withdraw) 10)
((peter-acc 'peter-password 'withdraw) 10)