(define (fixed-point f first-guess)
    (define tolerance 0.0000001)
    (define (close-enough? x y)
        (< (abs (- x y)) tolerance))
    (define (try guess)
        (let ((next (f (f guess))))
            (if (close-enough? guess next) 
                (/ (+ guess next) 2)
                (try next))))
                
    (try first-guess))